doctrine:
    dbal:
        driver: '%env(resolve:DATABASE_DRIVER)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Catalog:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Catalog/Doctrine/Entity'
                prefix: 'hex\Domain\Catalog'
                alias: App

