version: '3'

services:
  mysql:
    container_name: hex-mysql
    image: mysql:8
    ports:
    - "3306:3306"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=my-secret-pwd
    command: ["--default-authentication-plugin=mysql_native_password"]

  nginx:
    container_name: hex-nginx
    image: nginx:1.15-alpine
    ports:
    - "81:80"
    volumes:
      - .:/app:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: hex-php
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql